export const products = [
  {
    slug: "turmeric-cream",
    name: "Turmeric Cream",
    ingredients: [
      "water-aqua",
      "curcuma-longa-root-extract",
      "olea-europaea-fruit-oil",
      "aloe-barbadensis-leaf-extract",
      "arbutin",
      "hydrolyzed-sodium-hyaluronate",
      "dipotassium-glycyrrhizate",
      "sodium-lactate",
      "tocopherol",
      "hydrolyzed-collagen",
      "citric-acid",
      "curcumin",
      "salvia-miltiorrhiza-root-extract",
      "panthenol",
      "citrus-aurantium-dulcis-peel-oil",
      "sophora-angustifolia-root-extract",
      "allantoin",
    ],
  },

  {
    slug: "turmeric-serum",
    name: "Turmeric Serum",
    ingredients: [
      "water-aqua",
      "saccharomyces-ferment",
      "curcuma-longa-root-extract",
      "niacinamide",
      "centella-asiatica-extract",
      "xanthan-gum",
      "sodium-hyaluronate",
      "allantoin",
      "lavandula-angustifolia-extract",
      "arginine",
      "lactobacillus-ferment",
      "nonapeptide",
    ],
  },

  {
    slug: "turmeric-toner",
    name: "Turmeric Toner",
    ingredients: [
      "water-aqua",
      "glycerin",
      "curcuma-longa-root-extract",
      "centella-asiatica-extract",
      "aloe-barbadensis-leaf-extract",
      "sodium-citrate",
      "lactobacillus-ferment",
      "curcumin",
      "zinc-pca",
      "ascorbic-acid",
    ],
  },

  {
    slug: "turmeric-cleanser",
    name: "Turmeric Cleanser",
    ingredients: [
      "water-aqua",
      "glycerin",
      "cocos-nucifera-oil",
      "curcuma-longa-root-extract",
      "olea-europaea-fruit-oil",
      "centella-asiatica-extract",
      "aloe-barbadensis-leaf-extract",
      "lauryl-hydroxysultaine",
      "glutamic-acid",
      "citric-acid",
      "butyrospermum-parkii-butter",
      "curcumin",
      "avena-sativa-oat-extract",
      "inulin",
      "saccharomyces-ferment",
    ],
  },

  // BODY BUTTERS
  {
    slug: "original-body-butter",
    name: "Original Body Butter",
    ingredients: [
      "water-aqua",
      "glycerin",
      "olea-europaea-fruit-oil",
      "theobroma-cacao-seed-butter",
      "cocos-nucifera-oil",
      "aloe-barbadensis-leaf-extract",
      "butyrospermum-parkii-extract",
      "simmondsia-chinensis-seed-oil",
      "prunus-amygdalus-dulcis-oil",
      "argania-spinosa-kernel-oil",
      "butyrospermum-parkii-butter",
      "tocopherol",
      "hyaluronic-acid",
      "cera-alba-beeswax",
      "amethyst-powder",
    ],
  },

  {
    slug: "mango-body-butter",
    name: "Mango Body Butter",
    ingredients: [
      "water-aqua",
      "glycerin",
      "olea-europaea-fruit-oil",
      "theobroma-cacao-seed-butter",
      "cocos-nucifera-oil",
      "mangifera-indica-fruit-extract",
      "aloe-barbadensis-leaf-extract",
      "butyrospermum-parkii-butter",
      "simmondsia-chinensis-seed-oil",
      "prunus-amygdalus-dulcis-oil",
      "argania-spinosa-kernel-oil",
      "tocopherol",
      "hyaluronic-acid",
      "cera-alba-beeswax",
      "amethyst-powder",
    ],
  },

  {
    slug: "peach-body-butter",
    name: "Peach Body Butter",
    ingredients: [
      "water-aqua",
      "glycerin",
      "olea-europaea-fruit-oil",
      "theobroma-cacao-seed-butter",
      "cocos-nucifera-oil",
      "prunus-persica-fruit-extract",
      "aloe-barbadensis-leaf-extract",
      "butyrospermum-parkii-butter",
      "simmondsia-chinensis-seed-oil",
      "prunus-amygdalus-dulcis-oil",
      "argania-spinosa-kernel-oil",
      "tocopherol",
      "hyaluronic-acid",
      "cera-alba-beeswax",
      "amethyst-powder",
    ],
  },

  {
    slug: "citrus-body-butter",
    name: "Citrus Body Butter",
    ingredients: [
      "water-aqua",
      "glycerin",
      "olea-europaea-fruit-oil",
      "persea-gratissima-oil",
      "cocos-nucifera-oil",
      "citrus-aurantium-dulcis-peel-oil",
      "aloe-barbadensis-leaf-extract",
      "butyrospermum-parkii-butter",
      "centella-asiatica-extract",
      "prunus-amygdalus-dulcis-oil",
      "argania-spinosa-kernel-oil",
      "tocopherol",
      "hyaluronic-acid",
      "ascorbic-acid",
      "cera-alba-beeswax",
    ],
  },
];
